export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 prose prose-headings:font-bold prose-a:text-brand">
      <h1>Terms of Service</h1>
      <p className="text-sm text-gray-500">Last updated: [DATE — TODO]</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of the
        MotoManager mobile application and website (together, the
        &quot;Service&quot;), provided by [Your Business Name — TODO]
        (&quot;MotoManager&quot;, &quot;we&quot;, &quot;us&quot;). By creating
        an account or using the Service, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        MotoManager is a subscription software tool for bike and scooter
        rental shop owners to manage rentals, customers, fleet, staff, and
        related business operations, including generating rental receipts.
      </p>

      <h2>2. Accounts &amp; staff access</h2>
      <ul>
        <li>
          Shop Owners are responsible for maintaining the confidentiality of
          their account credentials and those of any staff accounts they
          create.
        </li>
        <li>
          Shop Owners are responsible for all activity under their account,
          including actions taken by staff members they grant access to.
        </li>
        <li>
          We may suspend accounts that we reasonably believe are being used
          fraudulently or in violation of these Terms.
        </li>
      </ul>

      <h2>3. Subscriptions &amp; billing</h2>
      <ul>
        <li>
          MotoManager is offered on a subscription basis (Basic and Pro
          plans, billed monthly or annually). Current pricing is shown on
          our Pricing page and within the app.
        </li>
        <li>
          Payments and recurring billing are processed via Razorpay. By
          subscribing, you authorize recurring charges to your selected
          payment method (card/UPI autopay/netbanking) until you cancel.
        </li>
        <li>
          Subscriptions automatically renew at the end of each billing
          period unless cancelled before the renewal date.
        </li>
        <li>
          You can cancel your subscription at any time from within the app.
          Cancellation takes effect at the end of the current billing
          period; we do not provide prorated refunds for partial periods
          except where required by law. [TODO: confirm refund policy.]
        </li>
        <li>
          We may change subscription pricing with prior notice; continued
          use after a price change constitutes acceptance.
        </li>
      </ul>

      <h2>4. Customer data &amp; receipts (Shop Owner responsibilities)</h2>
      <ul>
        <li>
          Shop Owners are solely responsible for obtaining valid consent
          from their customers (renters) before capturing ID proof, driving
          licence photos, and digital signatures via the app.
        </li>
        <li>
          Shop Owners are responsible for the accuracy of rental terms and
          conditions included in generated receipts (including damage
          charges, late return penalties, and traffic violation liability
          clauses), and for ensuring such terms comply with applicable law
          and are enforceable in their jurisdiction.
        </li>
        <li>
          Receipts generated by MotoManager are provided as a convenience
          tool. We do not guarantee the legal enforceability of any specific
          clause and recommend Shop Owners review their terms with a legal
          advisor.
        </li>
        <li>
          Shop Owners must comply with the Digital Personal Data Protection
          Act, 2023 and other applicable data protection laws when handling
          customer data through the Service.
        </li>
      </ul>

      <h2>5. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose, including discriminatory blacklisting of customers based on protected characteristics</li>
        <li>Attempt to access another shop&apos;s data without authorization</li>
        <li>Reverse-engineer, resell, or white-label the Service without our written consent</li>
        <li>Upload malicious code or attempt to disrupt the Service</li>
      </ul>

      <h2>6. Data &amp; cloud storage</h2>
      <p>
        The Service uses Supabase for cloud data storage and synchronization
        across devices. While we take reasonable steps to protect your data
        (see our Privacy Policy), you are responsible for maintaining your
        own backups of critical business records where practical.
      </p>

      <h2>7. Service availability</h2>
      <p>
        We aim to keep the Service available at all times but do not
        guarantee uninterrupted access. We are not liable for losses arising
        from downtime, internet connectivity issues, or third-party service
        outages (e.g. Supabase, Razorpay, app stores).
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, MotoManager and its
        operators shall not be liable for any indirect, incidental, or
        consequential damages arising from your use of the Service,
        including disputes between Shop Owners and their customers, vehicle
        damage, or loss of revenue. Our total liability for any claim shall
        not exceed the subscription fees paid by you in the 3 months
        preceding the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate access to the Service for breach of
        these Terms. Upon termination, your right to use the Service ceases,
        though we will retain data per our Privacy Policy and applicable
        retention requirements.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the
        Service after changes take effect constitutes acceptance of the
        revised Terms.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These Terms are governed by the laws of India. Courts at [City —
        TODO, e.g. Dehradun, Uttarakhand] shall have exclusive jurisdiction.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these Terms, contact us at{" "}
        <a href="mailto:support@motomanager.app">support@motomanager.app</a>{" "}
        [TODO: confirm contact email and registered business details].
      </p>
    </div>
  );
}
